const SELECTED_PLAN = "SELECTED_PLAN";
const NEW_PLAN = "NEW_PLAN";
const NEW_MAP = "NEW_MAP";
const CHANGE_FLOOR = "CHANGE_FLOOR";
const ADD_FLOOR = "ADD_FLOOR";
const SET_NOTIFICATION = "SET_NOTIFICATION";

export {
  SELECTED_PLAN,
  NEW_PLAN,
  NEW_MAP,
  CHANGE_FLOOR,
  ADD_FLOOR,
  SET_NOTIFICATION,
};
